In [20]:
#Create two vectors (A and B), where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() 
#function to create a 2 x 3 matrix from the vectors. Based on the output, determine the appropriate function to use

A<-c(1,2,3)
B<-c(4,5,6)

In [21]:
matrix.AB<-rbind(A, B)

In [23]:
class(matrix.AB)

[1] "matrix"

In [22]:
matrix.AB

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

In [7]:
#Create a 3 x 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow
#argument in the matrix() function call. Assign this matrix to the variable *mat

mat<-matrix(1:9, byrow=FALSE, nrow=3)

In [8]:
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [11]:
#Confirm that mat is a matrix

class(mat)

[1] "matrix"

In [24]:
#Create a 5 x 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the
#numbers 1-5

mat2<-matrix(1:25,byrow=TRUE,nrow=5)

In [25]:
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [27]:
#Use index notation to grab a subsection of mat2 that replicates the output
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [29]:
#Use index notation to grab a subsection of mat2 that replicates the output
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

In [33]:
sum(mat2)

[1] 325

In [34]:
help(runif)

Uniform                 package:stats                  R Documentation

_T_h_e _U_n_i_f_o_r_m _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     These functions provide information about the uniform distribution
     on the interval from 'min' to 'max'.  'dunif' gives the density,
     'punif' gives the distribution function 'qunif' gives the quantile
     function and 'runif' generates random deviates.

_U_s_a_g_e:

     dunif(x, min = 0, max = 1, log = FALSE)
     punif(q, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     qunif(p, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     runif(n, min = 0, max = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If 'length(n) > 1', the length is
          taken to be the number required.

min, max: lower and upper limits of the distribution.  Must be finite.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x],
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If 'min' or 'max' are not specified they assume the default values
     of '0' and '1' respectively.

     The uniform distribution has density

                             f(x) = 1/(max-min)                         
     
     for min <= x <= max.

     For the case of u := min == max, the limit case of X == u is
     assumed, although there is no density in that case and 'dunif'
     will return 'NaN' (the error condition).

     'runif' will not generate either of the extreme values unless 'max
     = min' or 'max-min' is small compared to 'min', and in particular
     not for the default arguments.

_V_a_l_u_e:

     'dunif' gives the density, 'punif' gives the distribution
     function, 'qunif' gives the quantile function, and 'runif'
     generates random deviates.

     The length of the result is determined by 'n' for 'runif', and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than 'n' are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

_N_o_t_e:

     The characteristics of output from pseudo-random number generators
     (such as precision and periodicity) vary widely.  See
     '.Random.seed' for more information on R's random number
     generation algorithms.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'RNG' about random number generation in R.

     Distributions for other standard distributions.

_E_x_a_m_p_l_e_s:

     u <- runif(20)
     
     ## The following relations always hold :
     punif(u) == u
     dunif(u) == 1
     
     var(runif(10000))  #- ~ = 1/12 = .08333

In [36]:
random<-runif(20, min=0, max=100)

In [37]:
random.matrix<-matrix(random,byrow=TRUE,nrow=4)

In [38]:
random.matrix

[,1]     [,2]      [,3]       [,4]     [,5]     
[1,] 19.21863 89.004681  0.4865572 22.74618 73.160397
[2,] 98.34778  1.787171 58.2633563 43.14330  5.240375
[3,] 92.72960 27.852748 96.9785646 93.46271 95.908941
[4,] 39.41819 44.525527 24.1405971 90.36085  1.926503